### ISSUE TITLE
Any difference from wyhash?

### ISSUE THREAD

**Issue by MeteorsLiu** [Nicoshev/rapidhash#11]
I compare the code with wyhash, it seems that there's less changes about algorithm.

Same mum function, but  more seeds?

It looks like an extended version of wyhash, may i ask what's the improvement? (no paper to disscus about it?)

**Comment by Nicoshev** [comment]
Regarding speed:
I thought that pointing to SMHasher and SMHasher3 performance measurements would be better than uploading any custom benchmark, as they are neutral third parties.
Their results show around 6% throughput increase compared to wyhash, similar to the measurements I've done.
The gain is mostly derived from the loop unrolling.

Regarding compatibility:
Support for MSVC was added.
More specifically, 64-bit multiplication on ARM64 is now done using the proper intrinsics.

Regarding quality:
rapidhash is listed as a 'passing hash' in SMHasher3 due to having no failing tests. In comparison, wyhash has 15 failing tests.
Using the length to xor the seed, decomposing the second loop into an explicit nested if that generates more entropy, aligning memory reads differently for lengths up to 16 bytes were some of the things that improved the quality
